- hosts: all
  gather_facts: false
  become: True
  become_method: sudo
  become_user: root

  tasks:
    - name: Add Docker apt key.
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/ubuntu/gpg"
        dest: /etc/apt/keyrings/docker.asc
        mode: "0644"
        force: false
