---
- hosts: all

  vars:
    config_files: /home/m/ansible/files

  tasks:
  - name: Create directory /opt/dockge/stacks/cup
    become: true
    ansible.builtin.file:
      path: /opt/dockge/stacks/cup
      state: directory
      mode: '0755'
      owner: root
      group: root
  
  - name: Create directory /opt/dockge/data/cup/
    become: true
    ansible.builtin.file:
      path: /opt/dockge/data/cup
      state: directory
      mode: '0755'
      owner: root
      group: root

  - name: Install Python requirements
    become: true
    ansible.builtin.pip:
      name: docker

  - name: "Copy Compose file"
    become: true
    template:
      src: "{{ config_files }}/cup.yml"
      dest: /opt/dockge/stacks/cup/docker-compose.yml
      owner: root
      group: root
      mode: 0644
