#https://galaxy.ansible.com/ui/standalone/roles/geerlingguy/docker/documentation/
---
- hosts: all
  become: true
  roles:
    - role: geerlingguy.docker
      vars:
        docker_edition: 'ce'
        docker_service_manage: true
        docker_service_state: started
        docker_service_enabled: true
        docker_restart_handler_state: restarted
        docker_install_compose: true
        docker_compose_version: "v2.30.3"

    - role: geerlingguy.pip
